@startuml Diagrama de clases de HydroSmart

' Interfaces
interface EventHandler {
    + onEvent()
}

interface CommandHandler {
    + handleCommand()
}

' Clases abstractas
abstract class Sensor {
    # pin: int
    # handler: EventHandler
    + onEvent()
    + setHandler()
}

abstract class Actuator {
    # pin: int
    # handler: CommandHandler
    + handleCommand()
    + setHandler()
}

abstract class Device {
    + onEvent()
    + handleCommand()
}

' Clases concretas
class DHT22Sensor {
    - humidity: float
    - temperature: float
    - dht: DHTesp
    + onEvent()
    + getHumidity()
    + getTemperature()
    + updateData()
}

class UltrasonicSensor {
    - triggerPin: int
    - echoPin: int
    - tankHeight: float
    - tankArea: float
    - currentVolume: float
    + onEvent()
    + getDistance()
    + getWaterHeigh()
    + getVolume()
    + updateData()
}


class LedActuator {
    - state: boolean
    + handleCommand()
    + turnOn()
    + turnOff()
}

class AutomaticIrrigationDevice {
    - dht22Sensor: DHT22Sensor
    - ledActuator: LedActuator
    - ultrasonicSensor: UltrasonicSensor
    + onEvent()
    + handleCommand()
    + handleVolumeChange()
    + handleEnviromentalChange()
    + getLed()
    + getDHT()
    + getUltrasonic()
}

' Relaciones de Implentacion de interfaces
EventHandler <|.. Sensor
CommandHandler <|.. Actuator
EventHandler <|.. Device
CommandHandler <|.. Device

' Relaciones de Herencia
Sensor <|-- DHT22Sensor
Sensor <|-- UltrasonicSensor
Actuator <|-- LedActuator
Device <|-- AutomaticIrrigationDevice

' Relaciones de Composición/Agregación (dependencia)
AutomaticIrrigationDevice --> DHT22Sensor
AutomaticIrrigationDevice --> UltrasonicSensor
AutomaticIrrigationDevice --> LedActuator
@enduml